const fs = require('node:fs');
const path = require('node:path');

type MemoryRecord = Record<string, any>;

function ensureDirectory(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

export function generateSkillFromCandidate(
  projectRoot: string,
  candidate: MemoryRecord
): string {
  const skillSlug = `ome-learned-${candidate.slug}`;
  const skillsLearnedDir = path.join(projectRoot, '.agent', 'workflows', 'learned');
  const skillPath = path.join(skillsLearnedDir, `${skillSlug}.md`);

  const evidence = Array.isArray(candidate.evidence) ? candidate.evidence : [];
  const executionDirectives = Array.isArray(candidate.executionDirectives)
    ? candidate.executionDirectives
    : ['Apply the learned fix pattern', 'Verify the fix resolves the issue'];

  const skillContent = `---
description: ${candidate.title || skillSlug} (Auto-generated from ${candidate.evidenceCount || 0} successful fixes)
generatedAt: ${new Date().toISOString()}
source: auto-evolution
patternId: ${candidate.patternId || candidate.slug}
---

# ${skillSlug}

${candidate.title || 'Learned Fix Pattern'}

Trigger: \`/${skillSlug}\`
Terminal equivalent: \`ome ${skillSlug.replace('ome-', '')} "<target>"\`

## Pattern Description

${candidate.summary || 'A fix pattern learned from successful bug resolutions'}

## Execution Directives

${executionDirectives.map((d: string) => `- ${d}`).join('\n')}

## Evidence

This skill was generated from ${candidate.evidenceCount || 0} successful bug fixes:

${evidence.map((e: MemoryRecord, i: number) => `${i + 1}. ${e.timestamp || 'unknown'} - ${e.changeId || 'unknown'}`).join('\n')}

## Usage

Before applying this pattern:
- Read \`.ome/config.json\` if present
- Read relevant files under \`.ome/rules/\`
- Verify the pattern applies to the current situation

Task:
- Apply the learned fix pattern
- Verify the fix resolves the issue
- Run tests to ensure no regressions
- Use the user arguments as the workflow input

Arguments:
- Claude/Cursor/Qoder/OpenCode style commands receive the user text after the command
- Codex skill clients should pass the same arguments after the skill name

If shell execution is available, prefer running the equivalent \`ome-*\` command and then continue from its guidance.

## Auto-generated

This skill was automatically generated by Oh My Engine's autonomous evolution system. If it doesn't work as expected, run \`ome evolve deprecate ${skillSlug}\` to remove it.
`;

  ensureDirectory(skillsLearnedDir);
  fs.writeFileSync(skillPath, skillContent, 'utf8');

  return skillPath;
}

module.exports = {
  generateSkillFromCandidate
};

export {};
